/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordbuilderRouteImport } from './routes/wordbuilder'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as HangmanRouteImport } from './routes/hangman'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as IndexRouteImport } from './routes/index'

const WordbuilderRoute = WordbuilderRouteImport.update({
  id: '/wordbuilder',
  path: '/wordbuilder',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const HangmanRoute = HangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/hangman': typeof HangmanRoute
  '/memory': typeof MemoryRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRoute
  '/wordbuilder': typeof WordbuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/hangman': typeof HangmanRoute
  '/memory': typeof MemoryRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRoute
  '/wordbuilder': typeof WordbuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flashcards': typeof FlashcardsRoute
  '/hangman': typeof HangmanRoute
  '/memory': typeof MemoryRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRoute
  '/wordbuilder': typeof WordbuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flashcards'
    | '/hangman'
    | '/memory'
    | '/quiz'
    | '/teacher'
    | '/wordbuilder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flashcards'
    | '/hangman'
    | '/memory'
    | '/quiz'
    | '/teacher'
    | '/wordbuilder'
  id:
    | '__root__'
    | '/'
    | '/flashcards'
    | '/hangman'
    | '/memory'
    | '/quiz'
    | '/teacher'
    | '/wordbuilder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HangmanRoute: typeof HangmanRoute
  MemoryRoute: typeof MemoryRoute
  QuizRoute: typeof QuizRoute
  TeacherRoute: typeof TeacherRoute
  WordbuilderRoute: typeof WordbuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordbuilder': {
      id: '/wordbuilder'
      path: '/wordbuilder'
      fullPath: '/wordbuilder'
      preLoaderRoute: typeof WordbuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangman': {
      id: '/hangman'
      path: '/hangman'
      fullPath: '/hangman'
      preLoaderRoute: typeof HangmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashcardsRoute: FlashcardsRoute,
  HangmanRoute: HangmanRoute,
  MemoryRoute: MemoryRoute,
  QuizRoute: QuizRoute,
  TeacherRoute: TeacherRoute,
  WordbuilderRoute: WordbuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
